inputs = [
    "My head’s bleeding a lot, and my vision’s blurry. My chest hurts when I breathe. Arms and legs seem okay, I think.",
    "I’m fine everywhere. No blood, no pain, just shaken up after the crash.",
    "My left arm’s got a deep cut, and it’s bleeding bad. My head’s okay, but my right leg’s pinned under debris.",
    "My leg’s missing after the blast. My head’s spinning, but no blood. Arms and torso are fine.",
    "I can’t feel my legs, they’re buried under rubble. My arms are okay, but my scalp’s cut open.",
    "My chest’s bleeding heavily, I’m pressing on it. My head, arms, and legs are alright, but I’m scared.",
    "My hands are sliced up and bleeding. My right wrist feels broken. Head, torso, and legs are fine.",
    "My forehead’s got blood running down, and I’m dizzy. My torso’s stuck under debris, can’t check it. Arms and legs are okay.",
    "My right thigh’s got a huge gash, blood’s everywhere. My head, arms, and torso are normal.",
    
    "My neck’s bruised and bleeding. My legs and arms are fine. Can’t tell about my back, it’s pinned.",
    "My head’s okay. My stomach’s bleeding and hurts bad when I move. Arms and legs are normal.",
    "My right arm’s gone, just severed in the explosion. My head, torso, and legs are okay.",
    "I don’t feel any injuries. Everything seems fine, no blood or pain.",
    "My left leg’s bleeding profusely, and I can’t move it. My head, torso, and arms are alright.",
    "My arms are cut up and bleeding. My head’s fine, but my legs are stuck under something heavy.",
    "My chest’s got a sharp pain, and there’s blood on my shirt. My head, arms, and legs are okay.",
    "My head’s bleeding from a cut on my temple. My torso, arms, and legs are normal, I think.",
    "My left hand’s crushed and bleeding. My head, torso, and legs are fine after the crash.",
    "I can’t see my torso, it’s covered by debris. My head, arms, and legs feel okay.",
    
    "My right leg’s got multiple cuts, bleeding a lot. My head, torso, and arms are normal.",
    "My head’s okay. My left arm’s twisted bad, can’t move it. Torso and legs are fine.",
    "My back’s bleeding, I can feel it. My arms, legs, and head are alright, but I’m freaking out.",
    "My legs are fine. My right hand’s bleeding and feels broken. Head and torso are okay.",
    "My head’s got a gash, and I’m seeing stars. My arms, torso, and legs are normal.",
    "My left arm’s missing after the blast. My head, torso, and legs seem okay.",
    "I can’t move my right leg, it’s bleeding bad. My head, torso, and arms are fine.",
    "My face is cut and bleeding. Everything else feels normal, thank God.",
    "My torso’s pinned, can’t check it. My head’s bleeding slightly. Arms and legs are okay.",
    "My arms are okay, but I can’t feel my legs at all. Head and torso seem fine.",
    
    "My head’s normal. My chest’s bleeding, and it hurts to breathe. Arms and legs are okay.",
    "My right arm’s fractured, and it’s bleeding. My head, torso, and legs are fine.",
    "My left leg’s stuck under debris, can’t move it. My head, torso, and arms are normal.",
    "I’m bleeding from my scalp, and my left arm’s cut bad. My torso and legs are okay.",
    "My head’s fine. My stomach’s got a deep cut, bleeding a lot. Arms and legs are normal.",
    "My right foot’s bleeding and feels broken. My head, torso, and arms are okay.",
    "My arms are trapped under rubble, can’t check them. My head, torso, and legs are fine.",
    "My head’s bleeding, and I’m dizzy. My torso’s okay, but my left leg’s bleeding bad.",
    "My chest’s fine. My right arm’s missing. My head and legs are normal after the explosion.",
    "My legs are bleeding from cuts. My head’s okay, but my torso’s pinned under debris.",
    
    "My head’s normal. My left hand’s bleeding and crushed. My torso and legs are fine.",
    "My right thigh’s torn open, blood’s pouring out. My head, arms, and torso are okay.",
    "I can’t feel my arms, they’re stuck. My head’s bleeding slightly. Torso and legs are okay.",
    "My back’s hurting bad, and there’s blood. My head, arms, and legs are normal.",
    "My head’s fine. My left leg’s bleeding and won’t move. My torso and arms are okay.",
    "My right arm’s bleeding and feels broken. My head, torso, and legs are normal.",
    "My scalp’s cut open, bleeding bad. My torso, arms, and legs are fine, I think.",
    "My chest’s bleeding, and it’s hard to breathe. My head, arms, and legs are okay.",
    "My left arm’s gone after the crash. My head, torso, and legs are normal.",
    "I can’t check my legs, they’re buried. My head’s bleeding, and my arms are fine.",
    
    "My head’s okay. My stomach’s bleeding bad. My arms and legs are normal.",
    "My right hand’s bleeding and hurts a lot. My head, torso, and legs are fine.",
    "My legs are stuck under debris, can’t feel them. My head, torso, and arms are okay.",
    "My head’s bleeding from a cut. My torso’s fine, but my right arm’s bleeding bad.",
    "My chest’s got a gash, bleeding heavily. My head, arms, and legs are normal.",
    "My left leg’s missing after the blast. My head, torso, and arms are okay.",
    "My arms are fine. My head’s bleeding, and my torso’s pinned under rubble.",
    "My right leg’s bleeding and feels broken. My head, torso, and arms are normal.",
    "My head’s fine. My left arm’s cut and bleeding. My torso and legs are okay.",
    "My back’s bleeding, I can feel it. My head, arms, and legs are normal.",
    
    "My head’s bleeding, and I’m woozy. My torso’s okay, but my legs are trapped.",
    "My right arm’s bleeding and won’t move. My head, torso, and legs are fine.",
    "My chest’s fine. My left leg’s bleeding bad. My head and arms are normal.",
    "My head’s normal. My right hand’s crushed and bleeding. My torso and legs are okay.",
    "My left thigh’s got a deep cut, bleeding a lot. My head, torso, and arms are fine.",
    "My arms are bleeding and stuck under debris. My head and legs are okay.",
    "My head’s bleeding from my forehead. My torso’s fine, but my right leg’s bleeding.",
    "My chest’s bleeding bad, hurts to breathe. My head, arms, and legs are okay.",
    "My right arm’s missing. My head, torso, and legs are normal after the crash.",
    "My legs are fine. My head’s bleeding slightly. My torso’s pinned under debris.",
    
    "My head’s okay. My left arm’s bleeding and feels broken. My torso and legs are fine.",
    "My right thigh’s bleeding heavily. My head, torso, and arms are normal.",
    "My head’s fine. My chest’s bleeding and hurts bad. My arms and legs are okay.",
    "My left hand’s bleeding and crushed. My head, torso, and legs are normal.",
    "My legs are trapped, can’t check them. My head’s bleeding, and my arms are fine.",
    "My head’s normal. My stomach’s bleeding bad. My arms and legs are okay.",
    "My right arm’s bleeding and fractured. My head, torso, and legs are fine.",
    "My head’s bleeding from a cut. My torso’s fine, but my left leg’s bleeding bad.",
    "My chest’s got a deep cut, bleeding a lot. My head, arms, and legs are normal.",
    "My left leg’s missing after the explosion. My head, torso, and arms are okay.",
    
    "My arms are okay. My head’s bleeding, and my torso’s stuck under debris.",
    "My right leg’s bleeding and feels broken. My head, torso, and arms are normal.",
    "My head’s fine. My left arm’s cut and bleeding bad. My torso and legs are okay.",
    "My back’s bleeding, I can feel it. My head, arms, and legs are normal.",
    "My head’s bleeding, and I’m dizzy. My torso’s okay, but my legs are pinned.",
    "My right arm’s bleeding and won’t move. My head, torso, and legs are fine.",
    "My chest’s fine. My left leg’s bleeding bad. My head and arms are normal.",
    "My head’s normal. My right hand’s crushed and bleeding. My torso and legs are okay.",
    "My left thigh’s got a deep cut, bleeding a lot. My head, torso, and arms are fine.",
    "My arms are bleeding and trapped under debris. My head and legs are okay.",
    
    "My head’s bleeding from my forehead. My torso’s fine, but my right leg’s bleeding.",
    "My chest’s bleeding bad, hurts to breathe. My head, arms, and legs are okay.",
    "My right arm’s missing. My head, torso, and legs are normal after the crash.",
    "My legs are fine. My head’s bleeding slightly. My torso’s pinned under debris.",
    "My head’s okay. My left arm’s bleeding and feels broken. My torso and legs are fine.",
    "My right thigh’s bleeding heavily. My head, torso, and arms are normal.",
    "My head’s fine. My chest’s bleeding and hurts bad. My arms and legs are okay.",
    "My left hand’s bleeding and crushed. My head, torso, and legs are normal.",
    "My right foot is crushed and bleeding. Head, torso, and arms are okay.",
    "I can't feel my arms, they are pinned under a heavy beam. My head is bleeding a little. Legs and torso seem fine.",
    
    "There's a large burn on my chest. Everything else seems untouched.",
    "My left leg is gone below the knee. My right arm has a deep gash. Head and torso are fine.",
    "I hit my head hard, it's throbbing. My back hurts badly. Arms and legs are okay.",
    "All my limbs are trapped. I can't see any injuries on them. My head and torso are clear.",
    "A piece of shrapnel hit my abdomen. My head feels fuzzy. Arms and legs are fine.",
    "My vision is blurry and my scalp is cut. My left hand is broken. Torso and legs are okay.",
    "I think my ribs are broken, it's hard to breathe. My legs are scraped up. Head and arms are fine.",
    "No visible injuries on my head, torso, arms or legs. Just feeling shaken.",
    "My right arm is completely severed. My left leg is also badly mangled and bleeding.",
    "My neck has a deep cut and is bleeding. My chest also has a cut. Arms and legs are fine.",
    
    "My head has a small scratch, no bleeding. My torso, arms and legs are fine.",
    "Both my legs are trapped under the car. I can't see them. My head is bleeding from a gash. Arms and torso are okay.",
    "My left hand is missing a few fingers. My right ankle is twisted and swollen. Head and torso are clear.",
    "I have a puncture wound in my side. My head is fine. My arms are scraped. My legs are okay.",
    "My left arm is broken and my right leg is also broken. Head and torso are surprisingly okay.",
    "There's a burn mark on my forehead. My left shin is bleeding. Torso and arms are fine.",
    "I landed on my back, it hurts a lot. My head hit the ground, I see stars. Arms and legs seem fine.",
    "My right leg is amputated at the hip. My left arm has minor cuts. Head and torso are fine.",
    "I can't assess my torso or legs, they are under debris. My head is fine. My arms have some bruises.",
    "My face is cut up badly. My chest feels tight but no visible wound. Arms and legs are okay.",
    "Both my hands are severely burned. My legs are fine. My head and torso are also fine.",
    "My left foot is gone. My right arm is trapped and I can't see it. Head and torso are okay.",
    
    "My ears are oozing blood but my body feels fine.",
    "There's fresh blood trickling from both ear canals, otherwise I'm okay.",
    "My abdomen is in intense pain, yet there are no cuts or bruises.",
    "I have severe stomach cramps but no external bleeding or lacerations.",
    "My thighs are covered in dark bruises, nothing else is injured.",
    "There are painful contusions on both legs, the rest of me feels normal.",
    "My palms are numb—I can’t sense anything in my hands.",
    "I can’t detect any feeling in my fingers or wrists.",
    "Both my legs have been severed, and the bleeding has stopped.",
    "I no longer have my legs; there’s no more blood flow.",
    
    "My right foot is bent at an odd angle and bleeding profusely.",
    "My right ankle is dislocated and blood is pouring out.",
    "Something struck my skull, and now my memory is blank.",
    "I took a blow to the head and can’t remember anything since.",
    "My abdomen is puffy and throbbing with pain.",
    "My belly feels distended and it hurts terribly.",
    "My right hand is missing after the explosion.",
    "They say my right hand was completely severed off.",  
    "I have a deep slice across my brow that's gushing blood.",
    "My forehead is lacerated and blood keeps pouring out.",

    "Debris is pinning my legs and I have no sensation below my hips.",
    "My lower limbs are trapped under concrete and they feel numb.",
    "Skin is the only thing holding my hand; it’s nearly detached.",
    "My hand is dangling by a flap of skin after it was trapped.",
    "I got struck hard in the skull and sternum, but my limbs feel uninjured.",
    "Both my head and chest took the impact; my arms and legs seem okay.",
    "There’s blood gushing from both of my legs and I am unable to move them.",
    "My legs are pouring blood and completely immobile.",
    "A jagged metal shard is embedded in my abdomen.",
    "I feel a sharp object lodged deep in my chest.",
    
    "My lower body is completely numb; I feel nothing below my hips.",
    "There’s zero sensation in my legs or feet.",
    "Both my arms and legs are lacerated, but my chest is uninjured.",
    "I have slashes on my legs and arms; there’s no damage to my torso.",
    "My palms are stiff and unresponsive, yet there’s no bleeding.",
    "I can’t move my hands—they’re locked up, though they aren’t bleeding.",
    "I have a ripping pain in my abdomen and spine.",
    "My belly and lower back feel like they've been shredded.",
    "There are deep bruises on my arms and chest, no blood visible.",
    "My chest and arms are black and blue, yet there’s no bleeding.",

    "My left thigh is smashed and I have injuries on both arms.",
    "The left side of my leg is flattened, and my arms are wounded too.",
    "I have a ripping pain in my abdomen and spine.",
    "My belly and lower back feel like they've been shredded.",
    "There are deep bruises on my arms and chest, no blood visible.",
    "My chest and arms are black and blue, yet there’s no bleeding.",
    "My left thigh is smashed and I have injuries on both arms.",
    "The left side of my leg is flattened, and my arms are wounded too.",
    "There’s blood pouring from my eye and it’s scorching with pain.",
    "My eye won’t stay open because it’s bleeding so badly.",
    
    "My lower back aches so fiercely I can’t straighten up.",
    "I have excruciating pain in my back that prevents me from sitting.",
    "My chest is soaked in blood and I’m lightheaded.",
    "There’s bleeding across my chest and I feel faint and woozy.",
    "I have no fingers on my left hand—they were ripped away.",
    "My scalp is cut and my hair is matted with blood.",
    "I’ve got a head injury and blood is soaked into my hair.",
    "My right hand was severed, and I have no other visible injuries.",
    "I’m missing my right hand; everything else seems fine.",
    
        "I hit my head on the dashboard. It’s bleeding and I feel dizzy. The rest of me seems fine.",
    "My right arm’s broken, I can’t move it at all. Legs are okay. No head injury that I know of.",
    "I’ve got deep cuts on both my thighs. There’s a lot of blood. My upper body and head are fine.",
    "Something pierced my chest. It hurts when I breathe. Arms, legs, and head are okay.",
    "There’s blood coming from my head and both my arms. My legs and torso are fine.",
    "I can’t move my legs, they’re numb and bleeding. The rest of my body seems unaffected.",
    "My left eye is swollen shut, and there’s blood from my scalp. No pain in torso or limbs.",
    "My ribs feel cracked, I can barely breathe. No bleeding in limbs or head.",
    "I lost sensation in my right hand and it’s turning blue. Everything else feels normal.",
    "Both legs are crushed under the wreckage. I don’t think I can move them. Other parts seem okay.",

    # Set 2
    "My head’s bleeding heavily and I can’t see straight. Arms, torso, and legs are fine.",
    "My left arm got ripped off in the blast. Everything else seems normal.",
    "I think something’s stuck in my chest. It hurts to move or breathe. Head and limbs seem okay.",
    "Both legs are pinned under debris. I can’t even check if they’re bleeding.",
    "There’s blood pouring from my right thigh and my left arm is cut badly. No head or torso injury.",
    "I lost both legs below the knee. There’s no way to stop the bleeding.",
    "Something heavy fell on my chest. I can’t move. I have no idea what’s happening with my arms or legs.",
    "My right arm is crushed and unusable. Legs and torso are normal. My head was not injured.",
    "There’s a deep wound on my scalp. Also, both my arms are stuck under the rubble and I can’t feel them.",
    "The whole lower half of my body is buried under rubble. I can’t tell what’s going on down there.",

    # Set 3
    "My head’s bleeding and my left leg is missing below the knee. My arms are pinned and I can’t move them. Chest feels fine.",
    "I can’t see anything, my head is pounding. My chest is crushed under the dashboard, and I can't feel my legs — they’re under the rubble.",
    "There’s blood on my arms and legs. My chest hurts when I inhale deeply. Head seems okay.",
    "I lost my right arm in the explosion, and both legs are stuck under debris. My head’s okay, but my chest is starting to feel tight.",
    "My scalp is cut and bleeding, and my chest is bruised. My left leg is crushed, and I can’t move my right arm.",
    "My torso is fine, but I can’t move either arm — they’re pinned under something. My head’s okay but both legs are bleeding badly.",
    "There’s a piece of metal lodged in my side. My left arm is bleeding, and my right leg is completely gone. I don’t know about my head.",
    "My arms are crushed and not responding. I can’t move my legs because they’re pinned under rubble. My head and torso feel normal.",
    "I have no memory of what happened, but I’m bleeding from the head and my legs feel numb. My chest and arms seem alright.",
    "My right leg is bleeding. My left leg is pinned under something. Head is pounding, and I think one arm is broken.",

    # Set 4
    "I bumped my head on the metal bar and there’s a small cut, but I’m otherwise fine.",
    "My right arm is broken in two places, I can’t lift it. Everything else feels okay.",
    "My left leg was severed below the knee, and my right arm is trapped under rubble so I can’t move it. Chest and head seem fine.",
    "I’m bleeding from the chest and both thighs. My torso is pinned under debris and I can’t check if it’s broken.",
    "I have a big bruise on my ribs and it hurts to breathe. Limbs and head are normal.",
    "My forehead is cut and bleeding. My right leg feels numb but it isn’t trapped. Arms and torso are fine.",
    "My left arm is crushed under the beam and I can’t feel it. My right leg has a deep gash with blood.",
    "I feel shaken but there’s no pain or bleeding anywhere.",
    "I lost my right hand completely. My head, chest, and legs are all fine.",
    "I can’t lift my head from under the car’s dashboard. My chest has a gash, and one leg is buried under metal.",

    # Set 5
    "My head hit the windshield and there’s a bump, but no bleeding. My arms and legs feel fine.",
    "I can’t move my right leg—it’s pinned under a fallen beam. Blood is pooling around it.",
    "My left hand is completely gone after the machine caught it. Other parts feel OK.",
    "There’s a deep slice across my abdomen and I’m losing a lot of blood. Limbs and head are fine.",
    "Both my shoulders are dislocated and I can’t lift my arms. Legs and torso are OK.",
    "I got struck in the chest and it’s painful to breathe. I don’t know about my legs under the rubble.",
    "My right ear is cut and bleeding. I can feel everything else normally.",
    "My left leg is numb but not trapped. No visible wounds. Chest and head are unhurt.",
    "My right arm is broken and bleeding. My left arm is fine, but my torso feels bruised.",
    "I’m buried up to my waist. I can’t see or move my lower body. Upper body and head are unharmed.",
    
    
    # Batch 1
    "There’s a cut above my left eyebrow and I’m seeing double. Everything else seems fine.",
    "My right arm is bleeding and I can’t lift it. My head, torso, and legs are okay.",
    "My chest hurts when I breathe, and I think I cracked some ribs. No pain in head or limbs.",
    "Both legs are numb and I can’t move them, but I’m not sure if they’re bleeding.",
    "My left leg is completely gone below the knee. I think everything else is okay.",
    "Something’s pressing down on my chest and I can’t breathe. I can’t tell if my arms or legs are injured.",
    "My head’s bleeding and both my arms feel broken. Legs and torso are fine.",
    "I can’t feel my hands, and they won’t move. Head, chest, and legs are okay.",
    "There’s a sharp pain in my lower back and my chest is bleeding. Arms and legs are okay.",
    "My entire lower body is stuck under the vehicle. I don’t know if anything down there is injured.",
    
    # Batch 2
    "My head is spinning and there’s blood running down my face. Everything else feels okay for now.",
    "I can’t move either of my legs—they’re under the rubble. My upper body seems fine.",
    "My left arm is gone, completely torn off. I don’t feel pain anywhere else.",
    "There’s something stuck in my abdomen and it hurts a lot. Arms, legs, and head seem alright.",
    "My right shoulder is dislocated, and I’m losing blood from that arm. The rest is okay.",
    "I was hit in the chest and now I can’t breathe properly. My vision is also getting blurry.",
    "My left leg is bleeding badly, and my right arm’s cut too. Head and torso are okay.",
    "I can’t feel or move anything below my waist. My head and arms are okay though.",
    "There’s a small wound on my forehead, and my right leg is bruised. Arms and chest are fine.",
    "My whole body’s shaking but I don’t see or feel any visible injuries.",
    
    # Batch 3
    "My head’s bleeding and my vision’s fading. Everything else feels okay for now.",
    "There’s a sharp pain in my chest, and I’m coughing up blood. Arms, legs, and head seem alright.",
    "Both arms are crushed and I can’t move them. My legs and head are okay.",
    "My legs are badly cut up, and I can’t stop the bleeding. Arms, torso, and head are fine.",
    "I can’t move anything below my chest. My arms are fine, but I don’t know what’s going on with my legs.",
    "Something is pressing against my ribs and I feel like they’re broken. No other injuries I can tell.",
    "I have deep cuts on my scalp and both thighs. Arms and torso are okay.",
    "I lost my left leg completely and can’t feel my right arm. The rest seems fine.",
    "My chest has a deep gash and my legs are stuck under rubble. Not sure what else is hurt.",
    "I’m bleeding from my forehead, and my left arm’s gone numb. Legs and torso are fine.",
    
    # Batch 4
    "My left leg is trapped under debris and I can’t tell if it’s bleeding. Everything else feels okay.",
    "There’s blood all over my chest and I’m having trouble breathing. My limbs and head are fine.",
    "My left arm is broken, and my right hand is missing. Chest, legs, and head seem okay.",
    "My skull feels like it cracked—I’m dizzy and bleeding from my head. No other injuries I notice.",
    "My legs are both crushed and I can’t move them. My upper body seems okay.",
    "There’s a cut on my right cheek, and I feel blood dripping from my chin. Arms, chest, and legs are fine.",
    "My whole left side is numb—arm and leg aren’t responding. Head and torso feel fine.",
    "I’ve lost my right leg below the knee and my left arm isn’t moving. I don’t think my head or chest are hurt.",
    "My chest is pinned under a beam. I can’t check my legs, but my head and arms are okay.",
    "There’s a deep gash on my left thigh and I think I broke my arm. Chest and head are fine.",
    
    # Batch 5
    "My arms are pinned under the wreckage and I can’t feel them. Head, chest, and legs seem okay.",
    "There’s blood running down my back and I feel a sharp pain near my spine. The rest feels normal.",
    "My left leg is missing, completely gone below the knee. Other body parts seem fine.",
    "I can’t see anything. My face is bleeding, and my chest feels tight. Not sure about my limbs.",
    "Both my hands are crushed and unresponsive. Head, torso, and legs feel okay.",
    "My lower half is under the rubble. I can’t move or feel anything from the waist down.",
    "There’s blood from my forehead, and my left leg is badly bruised. Arms and torso feel fine.",
    "My chest was struck hard—I can’t breathe properly. My arms and legs are fine. Head's a little foggy.",
    "My left arm is completely gone and I can’t move my right one either. Head, torso, and legs feel okay.",
    "My entire body hurts, but I only see blood coming from my scalp and thighs. Arms and torso feel fine.",
    
        ]


labels =[    
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    
    "Head: WOUND, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",
    "Head: WOUND, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",
    
    "Head: WOUND, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: AMPUTATION",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL", # Assuming neck injury maps to Head
    "Head: WOUND, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: WOUND",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: AMPUTATION", # Chest tight but no visible wound -> NORMAL
    "Head: NORMAL, Torso: NOT TESTABLE, Upper Extremities: WOUND, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: AMPUTATION",
    
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",  
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",


    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",

    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: NORMAL",


    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    
        "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",

    # Set 2
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NOT TESTABLE, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",

    # Set 3
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: AMPUTATION",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: AMPUTATION, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: WOUND, Lower Extremities: AMPUTATION",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: WOUND",

    # Set 4
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: AMPUTATION",
    "Head: NORMAL, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NOT TESTABLE, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",

    # Set 5
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    

    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NOT TESTABLE, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    
    # 11–20
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    
    # 21–30
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: AMPUTATION",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    
    # 31–40
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: AMPUTATION",
    "Head: NORMAL, Torso: NOT TESTABLE, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: WOUND, Lower Extremities: WOUND",
    
    # 41–50
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: AMPUTATION",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NOT TESTABLE, Lower Extremities: NOT TESTABLE",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NOT TESTABLE, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: NOT TESTABLE",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND",
    "Head: WOUND, Torso: WOUND, Upper Extremities: NORMAL, Lower Extremities: NORMAL",
    "Head: NORMAL, Torso: NORMAL, Upper Extremities: AMPUTATION, Lower Extremities: NORMAL",
    "Head: WOUND, Torso: NORMAL, Upper Extremities: NORMAL, Lower Extremities: WOUND"

    
    
]


easy_sentences, easy_labels = [], []
medium_sentences, medium_labels = [], []
hard_sentences, hard_labels = [], []

# Categorize
for sentence, label in zip(inputs, labels):
    normal_count = label.count("NORMAL")
    if normal_count >= 3:
        easy_sentences.append(sentence)
        easy_labels.append(label)
    elif normal_count == 2:
        medium_sentences.append(sentence)
        medium_labels.append(label)
    else:
        hard_sentences.append(sentence)
        hard_labels.append(label)

# Helper to format list line-by-line with double quotes
def format_list(name, items):
    formatted = f"{name} = [\n"
    for item in items:
        formatted += f'    "{item}",\n'
    formatted += "]\n\n"
    return formatted

# Write to file
with open("sorted_trauma_lists.txt", "w", encoding="utf-8") as f:
    f.write(format_list("easy_sentences", easy_sentences))
    f.write(format_list("easy_labels", easy_labels))
    f.write(format_list("medium_sentences", medium_sentences))
    f.write(format_list("medium_labels", medium_labels))
    f.write(format_list("hard_sentences", hard_sentences))
    f.write(format_list("hard_labels", hard_labels))

print("Lists saved to sorted_trauma_lists.txt.")